CREATE DATABASE IBOPE_TEST

CREATE TABLE IBOPE_TEST.DBO.Brand(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE
)

CREATE TABLE IBOPE_TEST.DBO.Equity(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(60),
    BRANDID INT NOT NULL,
    DESCRIPTION VARCHAR(100),
    REGISTER INT UNIQUE,
    CONSTRAINT FK_Equity_Brand FOREIGN KEY (BRANDID) REFERENCES DBO.Brand (ID)
)


CREATE TABLE IBOPE_TEST.DBO.SEC_TOKEN(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TOKEN VARCHAR(60) NOT NULL UNIQUE,
)

INSERT INTO IBOPE_TEST.DBO.SEC_TOKEN (TOKEN) VALUES ('LjkF3VdMHP87cVyu6sRHQvObKWexii3P')